 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;
import java.sql.*;

/**
 *
 * @author Joseph Mkonda
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        setDataToCards();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void setDataToCards(){
        Statement  st = null;
        ResultSet result = null;
        
        try{
            Connection con = DBConnection.getConnection();
            st = con.createStatement();
            result = st.executeQuery("select * from cholera_patient");
            result.last();
            TotalCase.setText(Integer.toString(result.getRow()));
            
            result = st.executeQuery("select * from cholera_patient where Status='"+"Admitted"+"'");
            result.last();
            Total_Hospitalised.setText(Integer.toString(result.getRow()));
            
            result = st.executeQuery("select * from cholera_patient where Status='"+"Dealth"+"'");
            result.last();
            Total_Dealth.setText(Integer.toString(result.getRow()));
            
            
        }catch(Exception e){
            e.printStackTrace();;
        }
        
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        jLabel1 = new JLabel();
        jPanel2 = new JPanel();
        jPanel3 = new JPanel();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        jPanel4 = new JPanel();
        jPanel5 = new JPanel();
        jLabel2 = new JLabel();
        jPanel6 = new JPanel();
        jLabel3 = new JLabel();
        jPanel7 = new JPanel();
        SignoutButton = new JLabel();
        jPanel8 = new JPanel();
        jLabel8 = new JLabel();
        jPanel9 = new JPanel();
        jLabel9 = new JLabel();
        jPanel10 = new JPanel();
        ManageCholeraButton = new JLabel();
        jPanel11 = new JPanel();
        ViewRecords = new JLabel();
        jPanel12 = new JPanel();
        jPanel13 = new JPanel();
        Total_Dealth = new JLabel();
        jLabel12 = new JLabel();
        jPanel14 = new JPanel();
        jPanel15 = new JPanel();
        TotalCase = new JLabel();
        jLabel15 = new JLabel();
        jLabel16 = new JLabel();
        jPanel16 = new JPanel();
        jLabel17 = new JLabel();
        jLabel18 = new JLabel();
        jPanel17 = new JPanel();
        jLabel19 = new JLabel();
        jLabel20 = new JLabel();
        jPanel18 = new JPanel();
        Total_Hospitalised = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new Color(102, 102, 255));
        jPanel1.setLayout(new AbsoluteLayout());

        jLabel1.setIcon(new ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_menu_48px_1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new AbsoluteConstraints(0, 10, 50, 60));

        jPanel2.setBackground(new Color(51, 51, 51));

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new AbsoluteConstraints(51, 0, -1, 70));

        jPanel3.setBackground(new Color(51, 51, 51));

        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new AbsoluteConstraints(50, -10, 2, 90));

        jLabel5.setFont(new Font("Segoe UI", 0, 25)); // NOI18N
        jLabel5.setForeground(new Color(255, 255, 255));
        jLabel5.setText("X");
        jLabel5.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new AbsoluteConstraints(1330, 20, 20, 20));

        jLabel6.setFont(new Font("Segoe UI", 1, 25)); // NOI18N
        jLabel6.setForeground(new Color(255, 255, 255));
        jLabel6.setText("Cholera Management System");
        jPanel1.add(jLabel6, new AbsoluteConstraints(90, 20, 380, 30));

        jLabel7.setFont(new Font("Segoe UI", 1, 25)); // NOI18N
        jLabel7.setForeground(new Color(255, 255, 255));
        jLabel7.setIcon(new ImageIcon(getClass().getResource("/adminIcons/adminIcons/male_user_50px.png"))); // NOI18N
        jLabel7.setText("Welcome,Admin");
        jPanel1.add(jLabel7, new AbsoluteConstraints(1020, 10, 260, 50));

        jPanel4.setBackground(new Color(51, 51, 51));

        jPanel5.setBackground(new Color(255, 102, 102));

        jLabel2.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new Color(255, 255, 255));
        jLabel2.setIcon(new ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel2.setText("    Home Page");

        GroupLayout jPanel5Layout = new GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 297, GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.setBackground(new Color(51, 51, 51));

        jLabel3.setBackground(new Color(51, 51, 51));
        jLabel3.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new Color(153, 153, 153));
        jLabel3.setText("    Features");

        GroupLayout jPanel6Layout = new GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 297, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.setBackground(new Color(51, 102, 255));

        SignoutButton.setBackground(new Color(255, 255, 255));
        SignoutButton.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        SignoutButton.setForeground(new Color(153, 153, 153));
        SignoutButton.setIcon(new ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Exit_26px_2.png"))); // NOI18N
        SignoutButton.setText("   Logout");
        SignoutButton.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                SignoutButtonMouseClicked(evt);
            }
        });

        GroupLayout jPanel7Layout = new GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(SignoutButton, GroupLayout.PREFERRED_SIZE, 297, GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel7Layout.setVerticalGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SignoutButton, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new Color(51, 51, 51));

        jLabel8.setBackground(new Color(51, 51, 51));
        jLabel8.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new Color(153, 153, 153));
        jLabel8.setIcon(new ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Library_26px_1.png"))); // NOI18N
        jLabel8.setText("    CMS Dashboard");

        GroupLayout jPanel8Layout = new GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 297, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new Color(51, 51, 51));

        jLabel9.setBackground(new Color(51, 51, 51));
        jLabel9.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new Color(255, 255, 255));
        jLabel9.setIcon(new ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Library_26px_1.png"))); // NOI18N
        jLabel9.setText("    CMS Dashboard");

        GroupLayout jPanel9Layout = new GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 297, GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel9Layout.setVerticalGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new Color(51, 51, 51));

        ManageCholeraButton.setBackground(new Color(51, 51, 51));
        ManageCholeraButton.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        ManageCholeraButton.setForeground(new Color(153, 153, 153));
        ManageCholeraButton.setIcon(new ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Book_26px.png"))); // NOI18N
        ManageCholeraButton.setText("   Manage Cholera");
        ManageCholeraButton.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                ManageCholeraButtonMouseClicked(evt);
            }
        });

        GroupLayout jPanel10Layout = new GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(jPanel10Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(ManageCholeraButton, GroupLayout.PREFERRED_SIZE, 297, GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel10Layout.setVerticalGroup(jPanel10Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ManageCholeraButton, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new Color(51, 51, 51));

        ViewRecords.setBackground(new Color(51, 51, 51));
        ViewRecords.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        ViewRecords.setForeground(new Color(153, 153, 153));
        ViewRecords.setIcon(new ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Return_Purchase_26px.png"))); // NOI18N
        ViewRecords.setText("   View Records");
        ViewRecords.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                ViewRecordsMouseClicked(evt);
            }
            public void mouseEntered(MouseEvent evt) {
                ViewRecordsMouseEntered(evt);
            }
        });

        GroupLayout jPanel11Layout = new GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(ViewRecords, GroupLayout.PREFERRED_SIZE, 297, GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel11Layout.setVerticalGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ViewRecords, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        GroupLayout jPanel4Layout = new GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel7, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel8, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel9, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel10, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel11, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(jPanel6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(jPanel7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(87, 87, 87)
                    .addComponent(jPanel8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(536, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(87, 87, 87)
                    .addComponent(jPanel9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(536, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(227, 227, 227)
                    .addComponent(jPanel10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(396, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(298, 298, 298)
                    .addComponent(jPanel11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(325, Short.MAX_VALUE)))
        );

        jPanel12.setBackground(new Color(255, 255, 255));
        jPanel12.setLayout(new AbsoluteLayout());

        jPanel13.setBorder(BorderFactory.createMatteBorder(15, 0, 0, 0, new Color(255, 102, 102)));
        jPanel13.setLayout(new AbsoluteLayout());

        Total_Dealth.setFont(new Font("Segoe UI", 1, 30)); // NOI18N
        Total_Dealth.setIcon(new ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Read_Online_26px.png"))); // NOI18N
        Total_Dealth.setText(" 300");
        jPanel13.add(Total_Dealth, new AbsoluteConstraints(60, 60, 120, 40));

        jPanel12.add(jPanel13, new AbsoluteConstraints(720, 60, 260, 140));

        jLabel12.setBackground(new Color(51, 51, 255));
        jLabel12.setFont(new Font("Segoe UI", 1, 20)); // NOI18N
        jLabel12.setForeground(new Color(51, 51, 255));
        jLabel12.setText("Total Dealth");
        jPanel12.add(jLabel12, new AbsoluteConstraints(730, 20, 130, 40));

        jPanel14.setBackground(new Color(255, 255, 255));
        jPanel14.setLayout(new AbsoluteLayout());

        jPanel15.setBorder(BorderFactory.createMatteBorder(15, 0, 0, 0, new Color(255, 102, 102)));
        jPanel15.setLayout(new AbsoluteLayout());

        TotalCase.setFont(new Font("Segoe UI", 1, 30)); // NOI18N
        TotalCase.setIcon(new ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_People_50px.png"))); // NOI18N
        TotalCase.setText(" 300");
        jPanel15.add(TotalCase, new AbsoluteConstraints(50, 60, 140, 40));

        jPanel14.add(jPanel15, new AbsoluteConstraints(30, 60, 260, 140));

        jLabel15.setBackground(new Color(51, 51, 255));
        jLabel15.setFont(new Font("Segoe UI", 1, 20)); // NOI18N
        jLabel15.setForeground(new Color(51, 51, 255));
        jLabel15.setText("Total Case");
        jPanel14.add(jLabel15, new AbsoluteConstraints(40, 16, 110, 40));

        jPanel12.add(jPanel14, new AbsoluteConstraints(0, 0, 290, 200));

        jLabel16.setBackground(new Color(51, 51, 255));
        jLabel16.setFont(new Font("Segoe UI", 1, 20)); // NOI18N
        jLabel16.setForeground(new Color(51, 51, 255));
        jLabel16.setText("Total Case");
        jPanel12.add(jLabel16, new AbsoluteConstraints(40, 16, 110, 40));

        jPanel16.setBorder(BorderFactory.createMatteBorder(15, 0, 0, 0, new Color(255, 102, 102)));
        jPanel16.setLayout(new AbsoluteLayout());

        jLabel17.setFont(new Font("Segoe UI", 1, 30)); // NOI18N
        jLabel17.setText("300");
        jPanel16.add(jLabel17, new AbsoluteConstraints(80, 60, 100, 40));

        jPanel12.add(jPanel16, new AbsoluteConstraints(30, 60, 260, 140));

        jLabel18.setBackground(new Color(51, 51, 255));
        jLabel18.setFont(new Font("Segoe UI", 1, 20)); // NOI18N
        jLabel18.setForeground(new Color(51, 51, 255));
        jLabel18.setText("Total Case");
        jPanel12.add(jLabel18, new AbsoluteConstraints(40, 16, 110, 40));

        jPanel17.setBorder(BorderFactory.createMatteBorder(15, 0, 0, 0, new Color(255, 102, 102)));
        jPanel17.setLayout(new AbsoluteLayout());

        jLabel19.setFont(new Font("Segoe UI", 1, 30)); // NOI18N
        jLabel19.setText("300");
        jPanel17.add(jLabel19, new AbsoluteConstraints(80, 60, 100, 40));

        jPanel12.add(jPanel17, new AbsoluteConstraints(30, 60, 260, 140));

        jLabel20.setBackground(new Color(51, 51, 255));
        jLabel20.setFont(new Font("Segoe UI", 1, 20)); // NOI18N
        jLabel20.setForeground(new Color(51, 51, 255));
        jLabel20.setText("Total Hospitalise");
        jPanel12.add(jLabel20, new AbsoluteConstraints(390, 20, 170, 40));

        jPanel18.setBorder(BorderFactory.createMatteBorder(15, 0, 0, 0, new Color(255, 102, 102)));
        jPanel18.setLayout(new AbsoluteLayout());

        Total_Hospitalised.setFont(new Font("Segoe UI", 1, 30)); // NOI18N
        Total_Hospitalised.setIcon(new ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Conference_26px.png"))); // NOI18N
        Total_Hospitalised.setText(" 300");
        jPanel18.add(Total_Hospitalised, new AbsoluteConstraints(70, 60, 110, 40));

        jPanel12.add(jPanel18, new AbsoluteConstraints(370, 60, 260, 140));

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 1805, GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel12, GroupLayout.PREFERRED_SIZE, 1044, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 68, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, GroupLayout.PREFERRED_SIZE, 687, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new Dimension(1400, 761));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void ManageCholeraButtonMouseClicked(MouseEvent evt) {//GEN-FIRST:event_ManageCholeraButtonMouseClicked
        ManageCholera manageCholera = new ManageCholera();
        manageCholera.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ManageCholeraButtonMouseClicked

    private void SignoutButtonMouseClicked(MouseEvent evt) {//GEN-FIRST:event_SignoutButtonMouseClicked
        SignIn signIn = new SignIn();
        signIn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SignoutButtonMouseClicked

    private void ViewRecordsMouseClicked(MouseEvent evt) {//GEN-FIRST:event_ViewRecordsMouseClicked
        PatientsRecord patientrecord = new PatientsRecord();
        patientrecord.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ViewRecordsMouseClicked

    private void ViewRecordsMouseEntered(MouseEvent evt) {//GEN-FIRST:event_ViewRecordsMouseEntered
        //jPanel1.setBackground(mouseEnterColor);
    }//GEN-LAST:event_ViewRecordsMouseEntered

    /*0
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel ManageCholeraButton;
    private JLabel SignoutButton;
    private JLabel TotalCase;
    private JLabel Total_Dealth;
    private JLabel Total_Hospitalised;
    private JLabel ViewRecords;
    private JLabel jLabel1;
    private JLabel jLabel12;
    private JLabel jLabel15;
    private JLabel jLabel16;
    private JLabel jLabel17;
    private JLabel jLabel18;
    private JLabel jLabel19;
    private JLabel jLabel2;
    private JLabel jLabel20;
    private JLabel jLabel3;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JPanel jPanel1;
    private JPanel jPanel10;
    private JPanel jPanel11;
    private JPanel jPanel12;
    private JPanel jPanel13;
    private JPanel jPanel14;
    private JPanel jPanel15;
    private JPanel jPanel16;
    private JPanel jPanel17;
    private JPanel jPanel18;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JPanel jPanel5;
    private JPanel jPanel6;
    private JPanel jPanel7;
    private JPanel jPanel8;
    private JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
